config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  # replacing this section of code with the above to prepare to recieve the FB callback
  # devise_for :users do
  #   #resources :comments, only: [:create, :destroy]
  #   resources :interests, only: [:new, :create, :destroy]
  #   resources :visits, only: [:new, :create]
  #end
  resources :user_phrases, only: :create
  resources :visits, only: :create
  root to: 'countries#index'
  resources :countries, only: [:index, :show]
  resources :user_places, only: [:create]
  post 'visas/:id/user_visas', to: 'user_visas#create', as: :new_user_visa

  get 'about', to: 'pages#about', as: 'about'
  get 'contact', to: 'pages#contact', as: 'contact'
  get 'profile/:id', to: 'pages#profile', as: 'profile'
  get 'visa_info', to: 'countries#visa_info', as: 'visa_info'
  post 'phrases/:id/user_phrases', to: "user_phrases#create", as: :new_user_phrase
  post 'countries/:id/visits', to: "visits#create", as: :country_visits

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
# class Comment < ApplicationRecord
#   belongs_to :user
#   belongs_to :commentable_id
#   validates :content, presence: true
# end

app/models/country.rb
class Country < ApplicationRecord
  has_many :places
  has_many :vocabularies
  geocoded_by :name
  after_validation :geocode, if: :will_save_change_to_name?
  has_many :visits
  has_many :users, through: :visits

  def visitors
    return users
  end

end

app/models/culture.rb
class Culture < ApplicationRecord
  belongs_to :country
end

app/models/culture_tip.rb
class CultureTip < ApplicationRecord
  belongs_to :culture
  validates :description, :title, :photo, presence: true
end

app/models/health.rb
class Health < ApplicationRecord
  belongs_to :country
end

app/models/health_tip.rb
class HealthTip < ApplicationRecord
  belongs_to :health
  validates :description, :title, presence: true
end

app/models/interest.rb
class Interest < ApplicationRecord
  belongs_to :user
  belongs_to :country
  validates :user_id, :country_id, presence: true
end

app/models/phrase.rb
class Phrase < ApplicationRecord
  belongs_to :vocabulary
  validates :english, :translation, presence: true
end

app/models/pin.rb
class Pin < ApplicationRecord
  belongs_to :place
  validates :latitude, :longitude, :description, :address, :photo, :title, :type, presence: true
end

app/models/place.rb
class Place < ApplicationRecord
  belongs_to :country
  #geocoded_by :address
  # after_validation :geocode, if: ->(obj) { !obj.latitude? && !obj.longitude? }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  devise :omniauthable, omniauth_providers: [:facebook]
  mount_uploader :photo, PhotoUploader
  has_many :user_phrases
  has_many :user_places
  has_many :user_visas
  has_many :interests
  has_many :visits
  # allows us to write user.visits
  has_many :countries, through: :interests

  has_many :phrases, through: :user_phrases

  def self.find_for_facebook_oauth(auth)
    user_params = auth.slice("provider", "uid")
    user_params.merge! auth.info.slice("email", "first_name", "last_name")
    user_params[:facebook_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)
    user_params = user_params.to_h

    user = User.find_by(provider: auth.provider, uid: auth.uid)
    user ||= User.find_by(email: auth.info.email) # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0, 20] # Fake password for validation
      user.save
    end

    return user
  end

  def likes_the_country(country)
    Interest.where(user: self, country: country).any?
  end
end

app/models/user_phrase.rb
class UserPhrase < ApplicationRecord
  belongs_to :user
  belongs_to :phrase
  after_create :set_interest

  def set_interest
    unless self.user.likes_the_country(self.phrase.vocabulary.country)
      Interest.create(user: self.user, country: self.phrase.vocabulary.country)
    end
  end

end

app/models/user_place.rb
class UserPlace < ApplicationRecord
  #belongs_to :country
  belongs_to :user
  belongs_to :place
  # has_many :users
  before_save :set_country
  after_create :set_interest
  def set_country
    self.country_id = self.place.country_id
  end

  def set_interest
    unless self.user.likes_the_country(self.place.country)
      Interest.create(user: self.user, country: self.place.country)
    end
  end
end

app/models/user_visa.rb
class UserVisa < ApplicationRecord
  belongs_to :user
  belongs_to :visa
end

app/models/vaccine.rb
class Vaccine < ApplicationRecord
  belongs_to :health
  validates :icon, :name, presence: true
end

app/models/visa.rb
class Visa < ApplicationRecord
  belongs_to :country
  has_many :visa_type
end

app/models/visa_type.rb
class VisaType < ApplicationRecord
  belongs_to :visa
  validates :type, :description, presence: true
end

app/models/visit.rb
class Visit < ApplicationRecord
  belongs_to :user
  belongs_to :country
  validates :user_id, :country_id, presence: true
end

app/models/vocabulary.rb
class Vocabulary < ApplicationRecord
  belongs_to :country
  has_many :phrases
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable"  content="yes">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- <link rel="stylesheet" type="text/css" href="your_website_domain/css_root/flaticon.css"> -->

    <link rel="stylesheet" href="https://use.typekit.net/iyr6bqv.css">
    <link rel="manifest" href="<%= asset_path 'manifest.json' %>">
    <title>trvlr.</title>
    <%= render 'shared/ios_pwa_links' %>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  <link rel="manifest" href="/manifest.json" />
<meta name="apple-mobile-web-app-capable" content="yes"></head>
  <body>
    <%= render 'shared/navbar' %>
  <div class="yield-content">
    <%= yield %>
  </div>
<!--     <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p> -->
    <%= render 'shared/flashes' %>
    <%= render 'shared/footer' %>

    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_KEY']}" %>

    <%#= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=#{ENV['GOOGLE_API_KEY']}" %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/about.html.erb
<p> I'm on the about us page</p>

app/views/pages/profile.html.erb
<div class="container" id="profile-container">
  <div class="profile-banner" style="background-image: url(https://res.cloudinary.com/dy0ujbaxb/image/upload/v1573784277/x1bxf9fpq1nevpdenmwn.png);">
    </div>
    <div class="container mt-6">
      <div class="d-flex flex-column bd-highlight mb-2">
        <div class="p-2 m-6 bd-highlight text-center">
          <% if @user.facebook_picture_url %>
          <%= image_tag @user.facebook_picture_url, class: "avatar-large dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <% elsif @user.photo %>
          <%= cl_image_tag @user.photo, class: "avatar-large dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <% else %>
          <%= image_tag "http://placehold.it/30x30", class: "avatar-large dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <% end %>
        </div>
      </div>

    <div class="profile-info">
      <div class="bd-highlight mr-8 ml-8">
        <h3 class="card-description text-center">Hello, I'm <%=@user.first_name%></h3>
      </div>
      <div class="profile-icons" id="social">
        <p><i class="fab fa-instagram"></i> <%= @user.instagram_user_name %></p>
        <p><i class="fab fa-facebook"></i> <%= @user.facebook_link %></p>
      </div>
      <div class="profile-icons" id="email">
        <p><i class="far fa-envelope"></i> <%= @user.email %></p>
      </div>
      <div id="bio">
        <p><%= @user.bio %></p>
      </div>
    </div>
  </div>

  <div class="profile-chapters">
    <h4 id="h4-profile">Interested in traveling to</h4>

  <!-- <h2 id="trtarget"> -->


<div class="countries-list">
  <div class="d-flex flex-wrap justify-content-center">
    <% @countries.each do |country| %>
        <%= link_to profile_path(country: country, anchor: "country-banner") do %>
          <div class="country-card profile-country-card" id="<%= 'country-banner' if @country == country %>" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= image_path country.photo %>)">
            <h2><%= country.name %></h2>
          </div>

          <% if @country == country %>

            <ul class="nav nav-pills no-shadow mb-3" id="pills-tab" role="tablist">
              <li class="nav-item ">
                <a class="nav-link" id="pills-vocabulary-tab" data-toggle="pill" href="#pills-vocabulary" role="tab" aria-controls="pills-vocabulary" aria-selected="true">Vocabulary</a>
              </li>
              <li class="nav-item">
                <a class="nav-link " id="pills-places-tab" data-toggle="pill" href="#pills-places" role="tab" aria-controls="pills-places">Places</a>
              </li>
            </ul>

            <div class="tab-pane fade" id="pills-vocabulary" role="tabpanel" aria-labelledby="pills-vocabulary-tab">
              <ul>
                <div class='phrases' style="grid-template-columns: 1fr;">
                  <% @phrases.each do |phrase| %>
                  <li style="display: flex;">
                    <div class='english'>
                      <p> <%= phrase.english %> : </p>
                    </div>
                    <div class='translated'>
                      <%= phrase.translation %>
                    </div>
                  </li>
                  <% end %>
                </div>
              </ul>
            </div>

            <div class="tab-pane fade" id="pills-places" role="tabpanel" aria-labelledby="pills-places-tab">
              <div class="row justify-content-around">
                <% @places.each do |user_place| %>
                  <div class="info-window col-xs-12">
                    <div class="d-flex mt-3" style='flex-direction: column;'>
                      <h1><%= user_place.place.name %></h1>
                      <img class="place-img" src="<%= user_place.place.photo%>" >
                      <p><b>City:</b> <%= user_place.place.city %></p>
                      <%= link_to 'More info', user_place.place.link, class: "btn btn-flat btn-primary" %>
                    </div>
                  </div>
                <% end %>
              </div>
            </div>

          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>

  <div class="profile-chapters">
    <h4 id="h4-profile">Traveled to</h4>
    <% if user_signed_in? && @user.id == current_user.id %>
      <p>Add places you’ve traveled to, so trvlrs can connect with you and ask questions about it</p>
      <%= form_tag visits_path, method: :post, class: "country-list" do |f| %>
      <%= select_tag 'country_id', options_for_select(Country.all.collect{ |c| [c.name, c.id] }) %>
      <%= hidden_field :visits, :latitude %>
      <%= hidden_field :visits, :longitude %>
      <%= submit_tag "Add", class: "btn btn-primary"  %>
      <% end %>
    <% end %>
    <% if @user.visits.any? %>
    <div class="row justify-content-center mx-auto">
      <% @countries_visited.each do |c| %>
      <div class="country-card col-12 profile-country-card" id="profile-country-card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= image_path c.photo %>)">
        <h2><%= c.name %></h2>
      </div>
      <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
    <div class="footer-links">
      <a href="#"><i class="fab fa-instagram"></i></a>
      <a href="#"><i class="fab fa-facebook"></i></a>
      <a href="#"><i class="fab fa-twitter"></i></a>
    </div>
    <div class="footer-copyright">
      trvlr.
    </div>
  </div>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_navbar.html.erb
<!--Navbar-->
<nav class="navbar navbar-light amber lighten-4 <%= 'mt-3' if params[:action] == 'profile' %>">

  <a class="navbar-brand" href="/">
    <%= image_tag 'trvlr-logo.svg'%>
  </a>
  <!-- Collapse button -->
  <button  href='#' class="navbar-toggler first-button" style="outline: none;" type="button" data-toggle="collapse" data-target="#navbarSupportedContent20"
    aria-controls="navbarSupportedContent20" aria-expanded="false" aria-label="Toggle navigation">
    <div class="animated-icon1">
      <span></span>
      <span></span>
      <span></span>
    </div>
  </button>
  <!-- Collapsible content -->
  <div class="collapse navbar-collapse
   <%= 'navbar-mb' if (params[:controller] == 'countries' &&  params[:action] == 'index') || (params[:controller] == 'pages' && params[:action] == 'profile')
 %>" id="navbarSupportedContent20">
    <!-- Links -->

    <ul class="navbar-nav mt-3">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Profile", profile_path(current_user), class:'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "Edit Profile", edit_user_registration_path, class:'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Logout', destroy_user_session_path, method: :delete, class:'nav-link' %>
        </li>
        <% else %>
        <li class="nav-item">
          <%= link_to 'Sign up', new_user_registration_path, class:'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Login', new_user_session_path, class:'nav-link' %>
        </li>
      <% end %>
      <li class="nav-item" style="color: black">
        <%= link_to 'Connect with other users', '#connect-with-other-users', class:'nav-link'%>
      </li>
      <li class="nav-item" style="color: black">
        <%= link_to 'About us', about_path, class:'nav-link'%>
      </li>
    </ul>
    <!-- Links -->

  </div>
  <!-- Collapsible content -->

</nav>


<!--/OLD NAVBAR-->
<!--     <button class="" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <i class="fas fa-bars" style="color:black; font-size:28px;">
      </i>
    </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto" style="background-color: #FFD364">
      <li class="nav-item nav-item-navbar active">
        <%#= link_to 'About us', about_path, class:'nav-box-link'%>
      </li>

      <#% if user_signed_in? %>
        <li class="nav-item nav-item-navbar">
          <div class="d-flex"> -->
          <!-- <#% if current_user.facebook_picture_url %>
          <%#= image_tag current_user.facebook_picture_url, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <#% elsif current_user.photo %>
          <%#= cl_image_tag current_user.photo, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <#% else %>
          <%#= image_tag "http://placehold.it/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <# end %> -->
<!--           <%#= link_to "Profile", profile_path(current_user), class:'nav-box-link' %>
        </div>
      </li>

      <li class="nav-item nav-item-navbar">
        <%#= link_to 'Logout', destroy_user_session_path, method: :delete, class:'nav-box-link' %>
      </li>
      <#% else %>

      <li class="nav-item nav-item-navbar">
        <#%= link_to 'Login', new_user_session_path, class:'nav-box-link' %>
      </li>

      <%# end %>
    </li>
    </ul>
  </div>
</div> -->