config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  # replacing this section of code with the above to prepare to recieve the FB callback
  # devise_for :users do
  #   #resources :comments, only: [:create, :destroy]
  #   resources :interests, only: [:new, :create, :destroy]
  #   resources :visits, only: [:new, :create]
  #end
  resources :user_phrases, only: :create
  resources :visits, only: :create
  root to: 'countries#index'
  resources :countries, only: [:index, :show]
  resources :user_places, only: [:create]
  post 'visas/:id/user_visas', to: 'user_visas#create', as: :new_user_visa

  get 'about', to: 'pages#about', as: 'about'
  get 'contact', to: 'pages#contact', as: 'contact'
  get 'profile/:id', to: 'pages#profile', as: 'profile'
  get 'visa_info', to: 'countries#visa_info', as: 'visa_info'
  post 'phrases/:id/user_phrases', to: "user_phrases#create", as: :new_user_phrase
  post 'countries/:id/visits', to: "visits#create", as: :country_visits

end

app/models/country.rb
class Country < ApplicationRecord
  has_many :places
  has_many :vocabularies
  geocoded_by :name
  after_validation :geocode, if: :will_save_change_to_name?
  has_many :visits
  has_many :users, through: :visits

  def visitors
    return users
  end

end

app/controllers/countries_controller.rb
require 'open-uri'
require 'json'

class CountriesController < ApplicationController
  def index
    @users = User.all
    @countries = Country.all
    @visits = Visit.all
    @markers = @visits.map do |visit|
      {
        lat: visit.latitude,
        lng: visit.longitude,
        infoWindow: { content: render_to_string(partial: "/countries/user_box", locals: { visit: visit }) },
        icon: helpers.asset_url('user_marker.svg')

      }
    end
  end

  def show
    @country = Country.find(params[:id])
    @users_visited = User.joins(:visits).where(visits: { country_id: @country.id }).uniq
    @photo = @country.photo
    @places = @country.places
    @marker = { lat: @country.latitude, lng: @country.longitude }
    @markers = @places.map do |place|
      {
        lat: place.latitude,
        lng: place.longitude,
        infoWindow: { content: render_to_string(partial: "/countries/places_box", locals: { place: place }) }
      }
    end
    @phrases = @country.vocabularies[0] ? @country.vocabularies[0].phrases : []
  end

  def visa_info
    @country = Country.find(params[:country_id])
    if params[:citizen_country].present?
      citizen_country = params[:citizen_country]
      country_code = @country.code
      @visa_info = get_visa_info(citizen_country, country_code)
    end
    respond_to do |format|
      format.html { render 'show', locals: { visa_info: @visa_info } }
      format.js
    end
  end

  def place
    @country = Country.find(params[:id])
    @places = Place.geocoded # returns places with coordinates
    @markers = @places.map do |place|
      {
        lat: place.latitude,
        lng: place.longitude
      }
    end
  end

  def get_visa_info(citizen_country, country_code)
    url = "http://requirements-api.sandbox.joinsherpa.com/v2/entry-requirements?citizenship=#{citizen_country}&destination=#{country_code}&language=en&key=AIzaSyACsHgC04uwmmgLYEJzQy53ME1pS_ujFMA"
    response = open(url).read
    datas = JSON.parse(response)
    # visa
    warning = datas["visa"].first["textual"]["class"] # if class=warning red font else black
    visa_required = datas["visa"].first["textual"]["text"][0] # you need a visa
    allowed_stay = datas["visa"].first["allowed_stay"] # 30 days
    type = datas["visa"].first["type"] # tourist
    requirement = datas["visa"].first["requirement"] # do an if statement if NOT_REQUIRED puts "Not required" else puts "Required" end
    info1 = datas["visa"].first["textual"]["text"][1] # "You may be eligible for an eVisa for your trip."
    info2 = datas["visa"].first["textual"]["text"][2] # "An eVisa is delivered electronically, and can be obtained online before your trip to Vietnam."
    # passport
    blank_pages = datas["passport"]["textual"]["blank_pages"]["text"][1] # Your passport must have one blank page.
    valid = datas["passport"]["textual"]["passport_validity"]["text"][1] # Your passport must be valid for six months at the time you enter Vietnam."

    # vaccination

    # currency
    currency_arrival = datas["currency"]["arrival"]
    currency_exit = datas["currency"]["exit"]

    { warning: warning,
      visa_required: visa_required,
      allowed_stay: allowed_stay,
      type: type,
      requirement: requirement,
      info1: info1,
      info2: info2,
      blank_pages: blank_pages,
      valid: valid,
      recom_vaccination: datas["vaccination"]["recommended"],
      risk_vaccination: datas["vaccination"]["risk"],
      currency_arrival: currency_arrival,
      currency_exit: currency_exit }
  end
end

# jesh's code for languages/phrases that was commented out
# @text = "hello"
# language_code = "pl"
# project_id = "corded-fact-258204"
# raise
# storage = Google::Cloud::Storage.new project_id: project_id
# storage.buckets.each do |bucket|
#   puts bucket.name
# end
# translate = Google::Cloud::Translate.new version: :v2, project_id: project_id
# @translation = translate.translate text, to: language_code

# @country.vocabularies[0].phrases : []
# @phrases = @country.vocabulary
# @country.vocabularies.phrases do |vocab|
#   {
#     original: vocabularies.original,
#     translation: vocabularies.translation
#   }
# end

app/views/countries/_continent.html.erb
<!-- <div class="countries-list">
  <div class="d-flex flex-wrap">
    <#% @countries.where(region: continent_adj).each do |country| %>
          <div class="country-card">
            <%#= link_to country_path(country) do %>
              <p><%#= country.name %></p>
              <%#= image_tag country.photo, class: "country-photo" %>
            <%# end %>
          </div>
    <%# end %>
  </div>
</div>
 -->

<div class="countries-list">
  <div class="d-flex flex-wrap justify-content">
    <% @countries.where(region: continent_adj).each do |country| %>
        <%= link_to country_path(country) do %>
          <div class="country-card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= image_path country.photo %>)">
            <h2><%= country.name %></h2>
          </div>
        <% end %>
    <% end %>
  </div>
</div>

app/views/countries/_culture.html.erb
<div class="culture">
  <div class="culture-tab">


    <i class="flaticon-airplane49" display: inline></i>
    <span class="flaticon-airplane49"></span>
<div class="culture">
  <div class="culture-tab">
    <p>Are you looking to plan your first trip to Mexico? There are several different aspects to consider before you go, from travel documents to health and safety concerns, and of course which destination to choose and what activities to pursue during your stay. Here are some resources to help you get your trip planned and figure out what you need, where you should go and what you should do, to help make your Mexico vacation a success.</p>
    <div class="tabs">
      <div class="tab">
        <input type="checkbox" id="chck1"  >
        <label class="tab-label" for="chck1" >
          <div class="culture-container">
            <%= image_tag 'icons/passport.png', width: 30, height: 30 %>
            <h4>Visa</h4>
          </div>
        </label>
        <div class="tab-content">
          <p>Early in your travel planning, you should make sure you have all the necessary documents to travel to Mexico. Passports can take a few months to process so make sure you apply far enough in advance. You probably won't need to apply in advance for a visa: when you enter the country you will be given a tourist card.</p>
        </div>
      </div>
      <div class="tab">
        <input type="checkbox" id="chck2">
        <label class="tab-label" for="chck2">
          <div class="culture-container">
            <%= image_tag 'icons/navigation.png', width: 30, height: 30 %>
            <h4>Going around</h4>
          </div>
        </label>
        <div class="tab-content">
          <p>Mexico is a much bigger country than most realize, so getting around can be a challenge. And while flights are often a decent value option, don’t forget about the excellent Mexico buses. It can be a great and affordable way to travel, plus you get to see Mexico’s gorgeous countryside. Mexico has a tiered bus system, with different classes of service offered at correspondingly higher prices. The higher classes are first (“primero”) and platinum (“platino”). The first class buses are nicer than most in the U.S., with comfortable seats and onboard restrooms. The platino buses, meanwhile, are worth a trip just to experience. Why? Well, the seats are equivalent to business class seats on an airline!</p>
        </div>
      </div>
      <div class="tab">
        <input type="checkbox" id="chck3">
        <label class="tab-label" for="chck3">
          <div class="culture-container">
            <%= image_tag 'icons/wallet.png', width: 30, height: 30 %>
            <h4>Money</h4>
          </div>
        </label>
        <div class="tab-content">
          <p>Low season in Mexico runs from late spring to early fall. The most expensive times to go are Christmas and New Year’s, which are especially popular with travelers. Prices stay high during the winter, when travelers head south to escape the cold, but fall after Easter. If you’re traveling to coastal areas, avoid hurricane season, which usually runs from June through October.</p>
        </div>
      </div>
      <div class="tab">
        <input type="checkbox" id="chck4">
        <label class="tab-label" for="chck4">
          <div class="culture-container">
            <%= image_tag 'icons/restaurant.png', width: 30, height: 30 %>
            <h4>Tipping</h4>
          </div>
        </label>
        <div class="tab-content">
          <p>At restaurants tipping between 10% and 15% is expected for good service. It's best to tip in cash, in the country's currency (peso). If the service is good, tip around 15%, or around 20% if the service is exceptional. Tip less if the service isn't up to standard.</p>
        </div>
      </div>
      <div class="tab">
        <input type="checkbox" id="chck5">
        <label class="tab-label" for="chck5">
          <div class="culture-container">
            <%= image_tag 'icons/cocktail-1.png', width: 30, height: 30 %>
            <h4>Water</h4>
          </div>
        </label>
        <div class="tab-content">
          <p>It’s a common warning for travelers in Mexico — be cautious of ice in beverages at restaurants, and avoid using tap water to brush your teeth as well. Drinking water in a new place can make you feel sick anywhere, not just in Mexico, but even residents in Mexico don’t trust their local tap water.</p>
        </div>
      </div>
      <div class="tab">
        <input type="checkbox" id="chck6">
        <label class="tab-label" for="chck6">
          <div class="culture-container">
            <%= image_tag 'icons/cocktail.png', width: 30, height: 30 %>
            <h4>Booze</h4>
          </div>
        </label>
        <div class="tab-content">
          <p> It is technically illegal to walk the streets of Mexico with an open container of alcohol, though it is not uncommon to see college kids on spring break meandering in public while drinking. In general, spring breakers are allowed to be drunk and loud as long as they don't endanger themselves or others. Still, they should be aware of the law.</p>
        </div>
      </div>
      <div class="tab">
        <input type="checkbox" id="chck7">
        <label class="tab-label" for="chck7">
          <div class="culture-container">
            <%= image_tag 'icons/flip-flops.png', width: 30, height: 30 %>
            <h4>Hygiene</h4>
          </div>
        </label>
        <div class="tab-content">
          <p>Speaking of bathroom humor, there is another habit that many of you may have to break when visiting Mexico: flushing your toilet paper. So the proper procedure is to toss it in the little waste bin that you’ll always find somewhere close to the throne. While some of the beach resorts and the nicer hotels in Mexico City may allow you to flush it away, most everywhere else it’s polite and proper to use the bin.</p>
        </div>
      </div>
      <div class="tab">
        <input type="checkbox" id="chck8">
        <label class="tab-label" for="chck8">
          <div class="culture-container">
            <%= image_tag 'icons/limousine.png', width: 30, height: 30 %>
            <h4>Transportation</h4>
          </div>
        </label>
        <div class="tab-content">
          <p>Buses in Mexico are generally safe, clean, and on time. There are “executive class” and “first class” buses that run on express routes and offer air conditioning, reclining seats, and movies — they’re even better than Greyhound. Second class buses usually make more stops, but make sense if your stop is a local one. Another plus? Buses in Mexico are great for sightseeing independently. A one-way bus ride to Chichén Itzá from Cancun costs about $15.</p>
        </div>
      </div>
      <div class="tab">
        <input type="checkbox" id="chck9">
        <label class="tab-label" for="chck9">
          <div class="culture-container">
            <%= image_tag 'icons/binoculars.png', width: 30, height: 30 %>
            <h4>Security</h4>
          </div>
        </label>
        <div class="tab-content">
          <p>Mexico has gotten a lot of negative attention on the safety front recently. And certainly it’s true that isolated parts of Mexico (which you were probably unlikely to visit anyway) have been plagued by a recent increase in cartel-associated violence. But, let’s be clear about one thing: traveling in most of Mexico is very safe. Millions of tourists visit Mexico every year, and violent incidents against tourists are actually very rare. Tourism is big business here and the government puts a lot of resources into ensuring the safety of visitors. Moreover, Mexicans are some of the most welcoming and friendly people on the planet – they aren’t out to get you!</p>
        </div>
      </div>
      <div class="tab">
        <input type="checkbox" id="chck10">
        <label class="tab-label" for="chck10">
          <div class="culture-container">
            <%= image_tag 'icons/beach.png', width: 30, height: 30 %>
            <h4>Fun</h4>
          </div>
        </label>
        <div class="tab-content">
          <p>Don’t fall into the trap of thinking that Mexico has a single culture or that you’ve seen the country just because you spent a weekend in Cancun or Cabo. Mexico is an ENORMOUS country with lots to see. It has over 128 million people. Mexico has mountains, deserts, cities, beaches, jungles, canyons, plains, and every sort of landscape you can imagine. Each part of the country has its own culture, food, and unique vibe. </p>
        </div>
      </div>
    </div>
  </div>
  </div>
</div>
</div>
  <div>Icons made by <a href="https://www.flaticon.com/authors/monkik" title="monkik">monkik</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a></div>

app/views/countries/_map.html.erb
<div
  id="map"
  data-markers="<%= @markers.to_json %>"
  data-marker="<%= @marker.to_json %>"
></div>

app/views/countries/_map_box.html.erb
<div class="info-window">
<div class="d-flex">
  <h1 style =""><%= place.name %></h1>
<div class='add'>
  <%= form_tag user_places_path do |f| %>
    <%= hidden_field_tag :place, place.id %>
    <%= submit_tag "add" %>
  <% end %>
    <%#= link_to "+", user_places_path(place), method: :post %>
</div>
</div>

<img class="place-img" src="<%= place.photo%>" >
<p><b>City:</b> <%= place.city %></p>
<%= link_to 'More info', place.link, class: "btn btn-flat btn-primary" %>

</div>

app/views/countries/_places_box.html.erb
<div class="info-window">
  <div class="d-flex">
    <h1 style =""><%= place.name %></h1>
      <div class='add' data-place="<%= place.id %>">
       <%= simple_form_for UserPlace.new, remote: true do |f| %>
        <%= f.input :place, as: :hidden, input_html: { value: place.id } %>
         <%= f.submit 'add', class: "btn btn-flat btn-primary" %>
       <% end %>
      </div>
  </div>

  <label>City:<%= place.city %></label>
  <img class="place-img" src="<%= place.photo%>" >
  <%= link_to 'More info', place.link, class: "btn btn-flat btn-primary" %>

</div>

app/views/countries/_search.html.erb
<%= simple_form_for :search, url: root_path, method: :get do |f| %>
  <div class="search-form-control form-group">
    <input class="form-control string required" type="text" name="search[query]" id="search_query" />
    <button name="button" type="submit" class="btn btn-flat">
      <i class="fas fa-search"></i> Search
    </button>
  </div>
<% end %>

app/views/countries/_user_box.html.erb
<div class="row" id="user-box">
  <% @users.each do |user| %>
    <% unless user == current_user %>
      <% unless user.visits.where(country_id: visit.country.id).empty? %>
        <div class="user-card col-4">
          <%= link_to profile_path(user), class:" d-flex" do  %>
            <% if user.facebook_picture_url %>
              <%= image_tag user.facebook_picture_url, class: "avatar" %>
            <% elsif !user.photo.blank? %>
              <%= cl_image_tag user.photo, class: "avatar"%>
            <% else %>
              <%= link_to 'Connect', profile_path(user) %>
              <%= image_tag "http://placehold.it/30x30", class: "avatar"%>
            <% end %>

          <% end %>
        </div>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/countries/_visa.html.erb
<p>Find out if you need a visa for <%= @country.name %>. Choose your citizenship and get information about passport requirements, allowed stay and duration of your visit.</p>
  <%= form_tag visa_info_path, method: :get, remote: true, class: "visa-from mb-3" do |f| %>
  <%= hidden_field_tag 'country_id', @country.id %>
    <select name="citizen_country" class="visa-form" style="background-color: #F4F4F4;/*  */padding: 9px 29px;/* display: -webkit-inline-box; *//* FONT-VARIANT: JIS83; *//* align-items: center; */border-color: transparent;">>
    <option value="" disabled selected>Choose your citizenship</option>
    <% Country.order(name: :ASC).each do |country| %>
      <option  value="<%= country.code %>"><%= country.name %></option>
    <% end %>
  </select>
  <%= submit_tag "Submit", class: "btn btn-primary"  %>
  <% end %>

<div id="visa-info-container">
  <%= render 'countries/visa_informations', visa_info: @visa_info %>
</div>

app/views/countries/_visa_informations.html.erb
<% if visa_info %>

  <p class="warning"><%= visa_info[:visa_required] %></p>

  <strong>How long am I allowed to stay?</strong>

    <% if visa_info[:allowed_stay] == nil %>
       <p>Depends on your visa requirements.</p>
    <% else %>
      <p><%= visa_info[:allowed_stay] %></p>
    <% end %>

  <strong>What visa options do I have?</strong>
  <p><%= visa_info[:info1] %> <%= visa_info[:info2] %></p>


  <h3 style="margin-top: 20px">Passport</h3>
  <strong>How many blank pages do I need?</strong>
  <p><%= visa_info[:blank_pages] %></p>

  <strong>How long must my passport be valid?</strong>
  <p><%= visa_info[:valid] %></p>

  <h3 style="margin-top: 20px">Vaccination</h3>

  <strong>Which vaccinations should I get?</strong>
    <% if visa_info[:risk_vaccination] == nil %>
    <p>No vaccination are needed.</p>
    <% else %>
    <% visa_info[:risk_vaccination].each do |risk| %>
    <p><%= risk["type"].gsub("_", " ").capitalize %></p>
    <% end %>
  <% end %>

  <strong>Which vaccinations are recomended?</strong>
    <% if visa_info[:recom_vaccination] == nil %>
    <p>No vaccination are recomended.</p>
    <% else %>
    <% visa_info[:recom_vaccination].each do |recom| %>
    <p><%= recom["type"].gsub("_", " ").capitalize %></p>
    <% end %>
  <% end %>
  <h3 style="margin-top: 20px">Currency</h3>

  <strong>Is there a restriction on bringing cash on arrival?</strong>
  <p><%= visa_info[:currency_arrival] %></p>

  <strong>Is there a restriction on taking cash when leaving?</strong>
  <p><%= visa_info[:currency_exit] %></p>

<% end %>

app/views/countries/_vocabulary.html.erb
<p>Handy phrases you may need in <%=@country.name%>.</p>
  <div class='phrases'>
    <% @phrases.each do |phrase| %>
      <div class='english'>
        <p> <%= phrase.english %> </p>
      </div>
      <div class='translated'>
        <%= phrase.translation %>
      </div>
      <div class="phrase-status" data-phrase="<%= phrase.id %>">

      <% if UserPhrase.find_by(user: current_user.id, phrase_id: phrase.id) %>
        <p id="added">added</p>
      <% else %>
        <div class='add-country'>
         <%= simple_form_for UserPhrase.new, remote: true do |f| %>
          <%= f.input :phrase, as: :hidden, input_html: { value: phrase.id } %>
          <%= f.input :country, as: :hidden, input_html: { value: @country.id } %>
          <%= f.submit 'add', class: "btn btn-flat btn-primary" %>
         <% end %>
        </div>
      <% end %>

      </div>
    <% end %>
  </div>

app/views/countries/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.0),rgba(0,0,0,0.2)), url(https://res.cloudinary.com/dy0ujbaxb/image/upload/v1573713250/utoduyoez9okattycsbb.png);">

  <div class="container" id="header-text">

    <h1>Everything you need to know for your next trip.</h1>
    <%#= link_to 'Login', new_user_session_path, class:'nav-link' %>
  </div>
</div>


<div class="info-section" id="continent-tabs">
  <div class="tab-bar">
    <ul class="nav nav-pills" id="pills-tab" role="tablist">
      <li class="nav-item">
        <a class="nav-link active" id="pills-africa-tab" data-toggle="pill" href="#pills-africa" role="tab" aria-controls="pills-africa" aria-selected="true">Africa</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="pills-asia-tab" data-toggle="pill" href="#pills-asia" role="tab" aria-controls="pills-asia" aria-selected="false">Asia</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="pills-europe-tab" data-toggle="pill" href="#pills-europe" role="tab" aria-controls="pills-europe" aria-selected="false">Europe</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="pills-americas-tab" data-toggle="pill" href="#pills-americas" role="tab" aria-controls="pills-americas" aria-selected="false">Americas</a>
      </li>
    </ul>
  </div>
<div class="sm-banner">
</div>
  <div class="tab-content" id="pills-tabContent pb-3">
    <div class="tab-pane fade show active" id="pills-africa" role="tabpanel" aria-labelledby="pills-africa-tab">
      <%= render 'continent', countries: @countries, continent_adj: "Africa" %>
    </div>
    <div class="tab-pane fade" id="pills-asia" role="tabpanel" aria-labelledby="pills-asia-tab">
    <%= render 'continent', countries: @countries, continent_adj: "Asia" %>
    </div>
    <div class="tab-pane fade show" id="pills-europe" role="tabpanel" aria-labelledby="pills-europe-tab">
    <%= render 'continent', countries: @countries, continent_adj: "Europe" %>
    </div>
    <div class="tab-pane fade" id="pills-americas" role="tabpanel" aria-labelledby="pills-americas-tab">
    <%= render 'continent', countries: @countries, continent_adj: "Americas" %>
    </div>
  </div>
</div>

<div class="info-section" id="connect-with-users">
  <div class="sm-banner">
    <h3 id="connect-with-other-users">Connect With Other Users</h3>
  </div>
  <div class="container">
    <%= render 'map' %>
  </div>
</div>

app/views/countries/show.html.erb
<div class='country-show'>
  <div class="country-banner d-flex flex-wrap justify-content-center" style="background-image: linear-gradient(rgba(0,0,0,0.3),rgba(0,0,0,0.3)), url('<%= cl_image_path @country.photo, crop: :fill %>'); background-size: cover; ">
    <%#= image_tag @country.photo, class:'show-banner' %>
    <h1 class='country-name'><%= @country.name %></h1>
  </div>
</div>

<ul class="nav nav-pills mb-3" id="country-show-tab" role="tablist">
  <li class="nav-item">
    <a class="nav-link active" id="pills-culture-tab" data-toggle="pill" href="#pills-culture" role="tab" aria-controls="pills-culture" aria-selected="true">Culture</a>
  </li>
<!--   <li class="nav-item">
    <a class="nav-link" id="pills-health-tab" data-toggle="pill" href="#pills-health" role="tab" aria-controls="pills-health" aria-selected="false">Health</a>
  </li> -->
  <li class="nav-item">
    <a class="nav-link" id="pills-vocabulary-tab" data-toggle="pill" href="#pills-vocabulary" role="tab" aria-controls="pills-vocabulary" aria-selected="false">Vocabulary</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="pills-visa-tab" data-toggle="pill" href="#pills-visa" role="tab" aria-controls="pills-visa" aria-selected="false">Visa</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="pills-places-tab" data-toggle="pill" href="#pills-places" role="tab" aria-controls="pills-places" aria-selected="false">Places</a>
  </li>
</ul>
<div class="tab-content" id="pills-tabContent">
  <div class="tab-pane fade show active" id="pills-culture" role="tabpanel" aria-labelledby="pills-culture-tab">
    <div class="content">
      <%= render 'culture' %>
    </div>
  </div>
<!--   <div class="tab-pane fade" id="pills-health" role="tabpanel" aria-labelledby="pills-health-tab">
    <div class="content">
      <#%= render 'health' %>
    </div>
  </div> -->
  <div class="tab-pane fade" id="pills-vocabulary" role="tabpanel" aria-labelledby="pills-vocabulary-tab">
    <div class="content">
      <%= render 'vocabulary' %>
    </div>
  </div>
  <div class="tab-pane fade" id="pills-visa" role="tabpanel" aria-labelledby="pills-visa-tab">
    <div class="content">
     <%= render 'visa' %>
    </div>
  </div>
  <div class="tab-pane fade" id="pills-places" role="tabpanel" aria-labelledby="pills-places-tab">
    <%#= render 'places_box', locals: { place:  } %>
<!--     <= render 'map' %>
    <#= render 'places_box', locals: { place:  } %> -->

    <div class="content">
          <%= render 'map' %>

      <%#= render 'places' %>
    </div>

  </div>
</div>

app/views/countries/visa_info.js.erb
var container = document.querySelector("#visa-info-container")

container.innerHTML = "<%= j render 'visa_informations', visa_info: @visa_info %>"